console_title_template = '{{ .Shell }} in {{ .Folder }}'
"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true
# Main prompt block
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # Current directory
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '{{ .Path }}'
    
    [blocks.segments.properties]
      style = 'full'

  # Git segment with default oh-my-posh styling
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    templates = [
      ' {{ .HEAD }}',
      '{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}',
      # '{{ if .Working.Changed }} ✏️ {{ .Working.String }}{{ end }}',
      # '{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}',
      # '{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}',
      # '{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    ]
    
    [blocks.segments.properties]
    fetch_status = true
    fetch_upstream_icon = true
    source = "cli"
    
  # Kubernetes context (only shows if context exists)
  [[blocks.segments]]
    type = 'kubectl'
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    template = ' {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'

# Prompt symbol
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    template = '❯'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
